baseURL       = "https://mastoryganizer.netlify.app/"
languageCode  = "en-us"
title         = "Mastoryganizer | Event Organizer"
theme         = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Portfolio"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Get in touch"
    url     = "contact"
    weight  = 4

# Site Params
[params]
  logo = "images/mastory-1.jpeg"
  favicon_icon = "images/favicon.ico"
  favicon_shortcut_icon = "images/mastory-1.jpeg"
  custom_stylesheets = []   # [ "scss/my_1.scss", "scss/my_2.scss" ]
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Mastoryganizer | Event Organizer"
  author = "Mastoryganizer"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://fabform.io/f/S_xjCiC"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "About the Project"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "wedding"
      title = "Wedding"

    [[params.contactForm.projectType]]
      value = "pre-wedding"
      title = "Pre Wedding"

    [[params.contactForm.projectType]]
      value = "birthday"
      title = "Birthday"

    [[params.contactForm.projectType]]
      value = "anniversary"
      title = "Anniversary"

    [[params.contactForm.projectType]]
      value = "festival"
      title = "Festival"

    [[params.contactForm.projectType]]
      value = "corporate"
      title = "Corporate"

    [[params.contactForm.projectType]]
      value = "other"
      title = "Other"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/IMG_4913.jpg"
    heading               = "We’re a Event Organizer to Make Your Event Memorables"
    tagline               = "SPECIAL MADE FOR YOU"
    primary_button        = "See Our Works"
    primary_button_url    = "portfolio"
    secondary_button      = "Connect with Us"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "OUR RECENT PROJECTS"
    subtitle  = "Creating memorable experiences and transforming complexity into clarity & beauty."
    view_project = "view project"
    more_works = "MORE WORKS"
    scroll_down = "scroll down"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Appointment Now"
    primary_button_url  = "contact"
    secondary_button    = "View Portfolio"
    secondary_button_url = "portfolio"

  [params.footer]
    params.footer.qr_print = false
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "Bogor Indonesia"
      email   = "mast.oryganizer@gmail.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Company"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Projects"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Youtube"
          url  = "https://youtube.com/@mastbaye?si=Lrs7Qi-cnILMpFwv"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://www.instagram.com/mast.oryganizer/"
        [[params.footer.social.link]]
          name = "Whatsapp"
          url  = "https://wa.me/+6281317990280?text=Hello%20Mast.Oryganizer!%20I%27m%20interested%20in%20your%20event%20organizing%20services%20and%20would%20like%20to%20learn%20more."
      # Footer Service
      [params.footer.service]
        title       = "We help you :"
        description = "To listen, understand, and strategize to your needs effectively and efficiently then create memorable experience"
      [params.footer.back_to_top]
        description = "I want to <br> visit again"
